[package]
name = "moq-sub"
description = "Media over QUIC"
authors = []
repository = "https://github.com/englishm/moq-rs"
license = "MIT OR Apache-2.0"

version = "0.4.4"
edition = "2021"

keywords = ["quic", "http3", "webtransport", "media", "live"]
categories = ["multimedia", "network-programming", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moq-transport = { path = "../moq-transport", version = "0.13" }
moq-native-ietf = { path = "../moq-native-ietf", version = "0.7" }
moq-catalog = { path = "../moq-catalog", version = "0.2" }
url = "2"

# Async stuff
tokio = { version = "1", features = ["full"] }

# CLI, logging, error handling
clap = { version = "4", features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
mp4 = "0.14"
anyhow = { version = "1", features = ["backtrace"] }
serde_json = "1"
